### PR TITLE
Declare as PROPRIETARY_MODULE

### PR DESCRIPTION
**Pull request by ix5**
Declaring `LOCAL_PROPRIETARY_MODULE` means the TransPower `.apk` files and libraries  will get installed to `/vendor` instead of `/system,` making it compatible with Treble ROMs.

Tested: Built all the Java apps and all the libraries without errors.

(using PROPRIETARY instead of VENDOR for compatibility with Nougat)

### CODE REVIEW

**Comment by jzoran** [comment]
Hi.

Thanks for the PR. It makes sense. Please add yourself to the AUTHORS file and give us a bit of time to verify with different versions - unfortunately offset time by our availability, but promise will be reasonable. :-)

**Comment by ix5** [comment]
> Please add yourself to the AUTHORS file

Sure, done.

> and give us a bit of time to verify with different versions - unfortunately offset time by our availability, but promise will be reasonable. :-)

No worries, this really only affects a few people who are doing treble builds, and they know how to cherry pick this for now.

**Comment by jzoran** [comment]
:thumbsup:

**Comment by ix5** [comment]
Lest I forget, if you're already taking a look, you might have to consider replacing OemHook calls in `libpower`. The interface [is slated for deprecation.](https://android.googlesource.com/platform/hardware/interfaces/+/android-9.0.0_r30/radio/deprecated/1.0/IOemHook.hal#24)

**Comment by jzoran** [comment]
We're already looking into it. Thanks.

**Comment by ix5** [comment]
Just a reminder to myself and others, this change means we need to install the priv-app permissions xml to `$(TARGET_COPY_OUT_VENDOR)`

**Pull request merged**
