### PR TITLE
[TRANSPOWER] [4/4] [WIP/RFC] Make SDK-28 compliant, use HookMediator for qcrild

### PR DESCRIPTION
**Pull request by MarijnS95**
Depends on https://github.com/sonyxperiadev/transpower/pull/14

Hi @jzoran,

This PR attempts to fix a multitude of things related to recent changes on SODP and Android API compatibility. Let me run through them sequentially:

Kumano requires `qcrild` instead of the (now legacy) `rild`, and all other platforms will follow soon. The new underlying `libril` does not expose `IOemHook` anymore, which in turn breaks the OemHooks in the Android telephony APIs (as currently used by TransPower). These are anyway hidden/deprecated, because the entire thing is scheduled to be removed in favour of vendor "extensions".

Qcrild implements that extension by means of a pretty much 1:1 copy of `IOemHook`, named `IQtiOemHook`. While it is possible to use HIDL under `SDK_VERSION := system_current` (as opposed to `system`) this connection is implemented in a separate application. Oemhooks will be used for more than just TransPower in the near feature but this interface does not support multiple clients concurrently.
The app is conveniently named `HookMediator` and takes care of handling multiple requests. It is implemented in a new repository that will be included soon:
https://github.com/MarijnS95/SonyOpenTelephony/
TransPower is altered to link against the generated AIDL interface and forward the `SET_TRANSMIT_POWER` call there. Since this is still new we should discuss API design: Naming, async or synchronous, and keeping things like `setTransmitPower` inside that app or have a generic `send` function that passes a raw `ByteBuffer` on. An async component could for example return the selected `serial` and report changes on a callback interface afterwards. Furthermore, error handling is not included yet either.

Finally all hidden/private/internal components have been replaced with publicly accessible ones, allowing to drop `PRIVATE_PLATFORM_APIS` and build TransPower for devices on SDK 28 and above.
I don't understand the `ifeq` that includes `telephony-common` on SDK >= 28 (483927d97a6b630731ba583ac06be92c3bb78111). This is in fact a `java:platform` library that cannot be linked against from `java:system`, which is what TransPower receives with `sdk_version: "system_current"`. There is no way to turn TransPower, which is a vendor application, into that. It is anyway unused after replacing `com.android.internal.telephony.Phone` with the the `HookMediator` interface, and could otherwise be replaced with `TelephonyManager`.

Tested by building all four apps for devices targeting SDK 26 and SDK 28, which have different `sdk_version` handling.
```shell
m TransPowerAcc TransPowerBase TransPowerProx TransPowerSensors
```
`TransPowerSensors` is tested on-device, together with `HookMediator` running.

### TODO:
- Bump the version to 2.3.0;
- Discuss API design of `IHooks`, as mentioned above;
- Handle service disconnections gracefully, improve `CompletableFuture` usage.

### Future:
TransPower is already branched out for Android 10 so we do not need to worry about backwards compatibility, unless you want to see that specifically.

- Convert all makefiles to `.bp`. This is much quicker to parse, and more convenient to read/edit without overcomplicating if/else branches.
  Unfortunately TransPower use files outside the module directory, which is not allowed. These files need to be wrapped in their own static library.
- Conversion to Kotlin: This is, IMO, much easier to write. I intend to convert at least `Transmitter.java` to improve readability after the introduction of the new hook mediator.

### CODE REVIEW

**Comment by jzoran** [comment]
Thanks for this PR! There are changes here that are long overdue and I've been planning for a while now.

I'd appreciate it if you split this PR in (at least) 3 separate PRs:
- switch to blueprint
- switch to androidx
- switch to new Hook

The switch to blueprint and androidx are not controversial and we will be able to merge it quite quickly, while the new API I'd like to take a closer look.

Thanks!

**Comment by MarijnS95** [comment]
While possible that is going to take some effort since most commits are linearly dependent on each other. The actual changes are split properly across commits, yet certain changes are ordered in such a way that they are convenient to apply (say, getting rid of `ifeq` barriers before migrating).
Making separate PRs based on features means reordering the commits and hence resolving a bunch of conflicts.

I propose the following commits/PRs, in this exact order:
- Migrate to androidx (necessary for API compliance) and other public APIs (HashSet)
- Drop `telephony-common` and switch to `TelephonyManager` as a stop-gap solution
  - This should result in a TransPower that satisfies all build-constaints, but fails (like it does now) when compiling for SDK >= 28
- Migrate to BP (likely a single PR for the changes right now, and another that converts the rest when I get around to it)
- Switch libpower over to the "HookMediator" service (conveniently last)

I will attempt to free up some time tomorrow night to clean this up. That hopefully includes bp-ifying all modules, but no promises there.

For now - if you have time - feel free to review individual commits and get some discussion going on the new service.

**Comment by monich** [comment]
Just noticed that these two pieces of code fill the buffer with different data:

https://github.com/sonyxperiadev/transpower/blob/master/libpower/src/com/sony/transmitpower/Transmitter.java#L58
https://github.com/MarijnS95/SonyOpenTelephony/blob/master/HookMediator/src/com/sony/opentelephony/hookmediator/HookMediatorService.kt#L68

Based on my experiments, neither actually works - the buffer formatted according to Transmitter.java results in RIL_E_INVALID_RESPONSE, the one formatted according to HookMediatorService.kt kills rild. That's Sony Xperia XA2, Android 8 something, i.e. calls are made via binder `IOemHook`/`IOemHookResponse` interfaces.

What is that parameter supposed to mean in the first place?

**Comment by MarijnS95** [comment]
@monich Indeed, that `Int.MAX_VALUE` should have been `Int.SIZE_BYTES` too. I'll correct that soon. I'm not fully surprised that rild crashes, it likely tries to read a way too large buffer going massively out of bounds :sweat_smile: . Though, that'd mean it has to be `Int.SIZE_BYTES * 2` since two integers (8 bytes total) follow.

The calls throw an invalid _response_ on k4.14 vendor libraries as well, both rild/qcrild. I assume librild simply fails to understand the response received from the underlying radio; otherwise I wouldn't see successful handling in that library in the first place. But that's something to investigate after correcting this buffer length.

As for the meaning, see the `validate` function at the bottom of `Transmitter.java`. I don't fully understand why key and value can be identical enumerations, though. One would assume the key to be the state (wifi on, incall, proximity sensor) and the value either a boolean or perhaps a distance (in case of the proximity sensor). You can follow the codepaths through TransPower to see where the values originate from.

**Comment by monich** [comment]
> @monich Indeed, that `Int.MAX_VALUE` should have been `Int.SIZE_BYTES` too. I'll correct that soon. I'm not fully surprised that rild crashes, it likely tries to read a way too large buffer going massively out of bounds  . Though, that'd mean it has to be `Int.SIZE_BYTES * 2` since two integers (8 bytes total) follow.

It does look like the length of the payload to me too, the question is what are the units - bytes, words or something else? `Transmitter.java` puts 4 there, which is what - number of half-words? I tried sending 8 or 2 and still got RIL_E_INVALID_RESPONSE, which leaves me confused. Without the equipment (which I don't have) to actually measure transmission power of the handset, I don't know what works and what doesn't. I was going to write a similar service for Sailfish OS running on Sony Xperia devices, but if the whole thing has no effect, that would be a total waste of time :/

**Comment by MarijnS95** [comment]
> the question is what are the units - bytes, words or something else

These are _usually_ bytes; I have never seen something like number of half-words but you never know with proprietary libraries :man_facepalming: 

Furthermore there are log lines indicating that this specific command is deprecated, and I couldn't find it anywhere in Stock either. Looks like more digging is in place, as there must be some sort of replacement.

Don't worry too much; Sony actually tests SODP for SAR compliance (which is why TransPower exists in the first place), and this PR serves to push that on to qcrild too. If it is found not work anymore (despite log messages indicating otherwise) it'll be back to the "drawing board" :wink:
However, keep in mind that they'll likely not go back to test new code/datastructures on older Android versions / firmware, so anything done here might be moot for a SFOS implementation.

**Comment by monich** [comment]
> > the question is what are the units - bytes, words or something else
> 
> These are _usually_ bytes; I have never seen something like number of half-words but you never know with proprietary libraries

Yeah, it must be bytes - unsolicited QOEMHOOK packets coming out of rild have number of bytes at that offset. How this Transmitter.java thing could have possibly worked then, with wrong size in the packet? There is something fishy here, that makes me think that this stuff never actually worked and I'm just wasting my time...

**Comment by MarijnS95** [comment]
> There is something fishy here, that makes me think that this stuff never actually worked and I'm just wasting my time...

@monich I fail to see the current "hurry" to implement this in SFOS way back on Android 8. Do you really expect this repo and all time spent maintaining it to be a joke? It originates from Sony internally (see readme) and there's no way they pass SAR tests based on good faith in the log messages only. For all we know the proprietary code might be parsing the data based on the type and actual array length, completely disregarding this field.

There is however a fair point to be made. The current code totally ignores the result of `invokeOemRilRequestRaw`, which fails with a `RadioError.REQUEST_NOT_SUPPORTED` on rild platforms (checked Nile and Ganges, on some random FW flashed over the past year):

```
W RILQ    : (0/783): RIL[0] qcril_send_request_response: UI <--- QCRIL_EVT_HOOK_SET_TRANSMIT_POWER (524489) Complete --- RIL [RID 0, Token id 28, Request Not Supported, Len 0 ]
```

I noticed this while doing the intermediary `TelephonyManager` migration, which handles any returned error code explicitly. Correcting the size field to 8 bytes changes nothing, as expected.

@jzoran Are you able to look into this and/or provide clarification? What I'd like to know is:
- Is this method still supported?
- If so, is it supposed to be working?
- What combinations of SODP "versions" and platforms/devices were measured?
- If there are alternatives, how does stock do it?
- Can you take care of updating the code in case it turns out to be completely broken? I likely don't have nearly the same amount of information readily available, requiring "other means" to get to the desired result.

For completeness, use the last commit [here](https://github.com/MarijnS95/transpower/commits/error-messages) to collect responses.

I'll think about submitting [the proposed PRs](https://github.com/sonyxperiadev/transpower/pull/11#issuecomment-597361794) at a later date or in a broken state. Leaving out the removal of `com.android.internal.telephony` nor ignoring the error are the way to go, IMO.

**Comment by monich** [comment]
> > There is something fishy here, that makes me think that this stuff never actually worked and I'm just wasting my time...
> 
> @monich I fail to see the current "hurry" to implement this in SFOS way back on Android 8.

There's no hurry, this task has been sitting in a backlog for quite some time. It's just that I finally had a chance to take a look at it. It's purely a coincidence that it happened at pretty much the same time when you submitted this patch. It really is, believe it or not.

> Do you really expect this repo and all time spent maintaining it to be a joke? It originates from Sony internally (see readme) and there's no way they pass SAR tests based on good faith in the log messages only. For all we know the proprietary code might be parsing the data based on the type and actual array length, completely disregarding this field.

Here's how my thinking goes. If the recipient completely ignored the length field then it wouldn't crash when you pass in a ridiculously large number. Since it does crash, then it must take that length into account, most likely copying just 4 out of 8 bytes of the payload. What's being taken for a value then? Probably random uninitialized memory or something that remained in the buffer from the previous packet - but not what's being passed in.

Now, how could the code which takes random input possibly pass real tests that perform real measurements of the transmission power?... One possibility is that there were no tests in the first place. Another possibility is that this is not the real code that works in the real device, the real code was tested and this one never was. Or there could be another error in the proprietary code which compensated for this one and the whole thing accidentally worked. Or small packets are being passed by pointer and the length is being ignored if you specify a number smaller than certain amount. There are all kinds of possibilities. It would be nice to know what's actually going on.

**Comment by MarijnS95** [comment]
@jzoran The requested PRs have been pushed, see #12 #13 #14. Please keep in mind the issues with `invokeOemRilRequestRaw` as mentioned above.

@monich Remember that I did not get any crashes here with this crazy large number; it has not been in TransPower either, that was [my own typo](https://github.com/sonyxperiadev/transpower/pull/11#issuecomment-597379817) specific to this PR.

**Comment by monich** [comment]
> @monich Remember that I did not get any crashes here with this crazy large number; it has not been in TransPower either, that was [my own typo](https://github.com/sonyxperiadev/transpower/pull/11#issuecomment-597379817) specific to this PR.

Yes, it was me getting those crashes when I was playing with crazy numbers on Sony Xperia XA2:
```
pid: 7139, tid: 7139, name: rild  >>> /vendor/bin/hw/rild <<<
signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x7e73b1b000
    x0   0000000000000000  x1   000000007fffffff  x2   6f646e6576007325  x3   702f6d6f63712f72
    x4   0000000000000010  x5   0000000000000000  x6   6f2e6c6e62702e71  x7   7f7f7f7f7f7f7f7f
    x8   0000000000000020  x9   0000007fd3fbcaf4  x10  0000007ef6762710  x11  0000007e73b1b000
    x12  0000000000000f48  x13  0000000000000f48  x14  0000000000000016  x15  0000000000000013
    x16  0000007ef67ff018  x17  0000007ef5f2eb54  x18  6e1bc05c928bb0ed  x19  0000007fd3fbe240
    x20  0000007e73b1a098  x21  0000007ef7e51820  x22  0000007ef8b2a0dc  x23  0000007ef8f30a40
    x24  0000007ef8b2a050  x25  0000007ef8f30a40  x26  0000007fd3fbe540  x27  0000000000000000
    x28  0000007fd3fbe770  x29  0000007fd3fbcb30  x30  0000007ef5ed2fd4
    sp   0000007fd3fbca90  pc   0000007ef5ed2f08  pstate 0000000080000000
    v0   0000007fd3fbce700000007fd3fbcef0  v1   ffffff80ffffffd80000007fd3fbce40
    v2   6e656c69735f7061732e6f696461722e  v3   00000000000000020000000000000000
    v4   00000000000000000000000000000000  v5   00000000000000000000000000000000
    v6   00000000000000000010000000000001  v7   80200802802008028020080280200802
    v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
    v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
    v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
    v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
    v16  40100401401004014010040140100401  v17  00000000100000010000100100020000
    v18  00000000000000000010000000000001  v19  00000000000000000000000000000000
    v20  00000000000000000000000000000000  v21  00000000000000000000000000000000
    v22  00000000000000000000000000000000  v23  00000000000000000000000000000000
    v24  00000000000000000000000000000000  v25  00000000000000000000000000000000
    v26  00000000000000000000000000000000  v27  00000000000000000000000000000000
    v28  00000000000000000000000000000000  v29  00000000000000000000000000000000
    v30  00000000000000000000000000000000  v31  00000000000000000000000000000000
    fpsr 00000010  fpcr 00000000

backtrace:
    #00 pc 0000000000186f08  /odm/lib64/libril-qc-qmi-1.so (qcril_qmi_print_hex+176)
    #01 pc 0000000000199b80  /odm/lib64/libril-qc-qmi-1.so (qcril_dispatch_event+88)
    #02 pc 00000000001a6ef0  /odm/lib64/libril-qc-qmi-1.so (qcril_execute_event+2960)
    #03 pc 00000000001a56d8  /odm/lib64/libril-qc-qmi-1.so (qmi_ril_fw_android_request_render_execution+1072)
    #04 pc 00000000001a0d1c  /odm/lib64/libril-qc-qmi-1.so (onRequest+13984)
    #05 pc 00000000001b98d8  /odm/lib64/libril-qc-qmi-1.so (onRequest_rid+56)
    #06 pc 0000000000022314  /vendor/lib64/libril.so (OemHookImpl::sendRequestRaw(int, android::hardware::hidl_vec<unsigned char> const&)+80)
    #07 pc 0000000000018c78  /system/lib64/android.hardware.radio.deprecated@1.0.so (android::hardware::radio::deprecated::V1_0::BnHwOemHook::_hidl_sendRequestRaw(android::hidl::base::V1_0::B
nHwBase*, android::hardware::Parcel const&, android::hardware::Parcel*, std::__1::function<void (android::hardware::Parcel&)>)+212)
    #08 pc 00000000000194ac  /system/lib64/android.hardware.radio.deprecated@1.0.so (android::hardware::radio::deprecated::V1_0::BnHwOemHook::onTransact(unsigned int, android::hardware::Parce
l const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+1320)
    #09 pc 0000000000011800  /system/lib64/libhwbinder.so (android::hardware::BHwBinder::transact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std
::__1::function<void (android::hardware::Parcel&)>)+132)
    #10 pc 0000000000015384  /system/lib64/libhwbinder.so (android::hardware::IPCThreadState::executeCommand(int)+576)
    #11 pc 000000000001508c  /system/lib64/libhwbinder.so (android::hardware::IPCThreadState::getAndExecuteCommand()+164)
    #12 pc 0000000000015794  /system/lib64/libhwbinder.so (android::hardware::IPCThreadState::joinThreadPool(bool)+60)
    #13 pc 0000000000001a3c  /vendor/bin/hw/rild (main+1116)
    #14 pc 00000000000a1c78  /system/lib64/libc.so (__libc_init+88)
    #15 pc 0000000000001540  /vendor/bin/hw/rild (_start_main+80)
```

**Comment by MarijnS95** [comment]
> > @monich Remember that I did not get any crashes here with this crazy large number; it has not been in TransPower either, that was [my own typo](https://github.com/sonyxperiadev/transpower/pull/11#issuecomment-597379817) specific to this PR.
> 
> Yes, it was me getting those crashes when I was playing with crazy numbers on Sony Xperia XA2:

That is merely saying that there is no real conclusion to be drawn, as it was a mistake in the first place.

Anyway, `qcril_qmi_print_hex`: Sounds like a generic method to print debug messages to me. It is very well possible that the actual handling of the request disregards the size field entirely and merely interprets the incoming data as a specific struct when `SET_TRANSMIT_POWER` is encountered. Proprietary code isn't really known for it's stellar bounds-checking or argument validation :man_shrugging: 

Anyway, let's wait for Monday and see what @jzoran has to say. This is getting borderline related to the PR or the questions we should be discussing.

**Comment by monich** [comment]
> Anyway, `qcril_qmi_print_hex`: Sounds like a generic method to print debug messages to me. It is very well possible that the actual handling of the request disregards the size field entirely and merely interprets the incoming data as a specific struct when `SET_TRANSMIT_POWER` is encountered. 

I like this theory :)

**Comment by konradybcio** [comment]
would be nice to revisit this, especially since ninges and yoshino are considered obsolete, maybe the issues were isolated to older modem stacks

**Comment by jerpelea** [comment]
@MarijnS95 please rebase

**Pull request closed without merging**
